Copy all files
wkoszek/rcli pull request #2
Opened 2022-06-14 15:18 UTC by ramin0x53

2022-06-14 15:41 UTC, wkoszek commented on Dockerfile
> +WORKDIR /go/src
Let's move this to the top

2022-06-15 19:55 UTC, wkoszek requested changes
Good work. This tool I'm sure will be useful for many people. Nothing is a jarring problem, but I know you want to learn, so I'm attaching my feedback. Let me know what you think.

2022-06-15 19:55 UTC, wkoszek commented on cli/cli.go
> +	fmt.Println("Commands:")
@ramin0x53 learn how to use Printf with a proper formatting string. It can do padding for you. https://golang.cafe/blog/golang-string-padding-example.html

2022-06-15 19:55 UTC, wkoszek commented on cli/cli.go
> +	if opts.Command == "configcl" {
If you want, just ask people for simple parameters from STDIN and write the config. Right now it's hard to understand it. Just ask for: server, port and pass and that's all. Write the config

2022-06-15 19:55 UTC, wkoszek commented on config/config.go
> +	homeDir, err := os.UserHomeDir()
You should write helper function: "GetConfigFilePath()" and use it everywhere. You duplicate the same code multiple times.

2022-06-15 19:55 UTC, wkoszek commented on cli/cli.go
> +
We may consider using a library like spf13/cobra.

It'd simplify your processing of command-line arguments I think. 

Another option you may consider is a table driven-approach: define a structure with function pointer, command, and a number of arguments this command takes, and you can do both:
- validation
- dispatching
in the same loop. If the function is found based on the name match, you execute the function. if not, you fail and print that the function isn't known

2022-06-15 19:55 UTC, wkoszek commented on config/config.go
> +//Check if config file exists
You rarely need this function. Your ReadConfig() can be used for checking presence. If it returns "file not found" it means file isn't there.

2022-06-15 19:55 UTC, wkoszek commented on redis/hash.go
> +package redis
I don't know how much you gain by adding those helper routines. You added 1 helper for each call. But the call is very similar each time, and it's just 1 line. Instead, we have 50 lines here.

Maybe try just calling the functions in the appropriate place instead.

2022-06-15 19:55 UTC, wkoszek commented on redis/keyvalue.go
> +package redis
same here

2022-06-15 19:55 UTC, wkoszek commented on redis/list.go
> +package redis
same here

2022-06-15 19:55 UTC, wkoszek commented on redis/redis.go
> +	switch data.Command {
If you just call the Redis functions here, it'd be better. Each of the calls returns the error, that you can handle after `switch`

2022-06-16 05:31 UTC, ramin0x53 commented on Makefile
> +install: build rmconfig
I know this won't work , I just wrote it to use in dockerfile

2022-06-17 19:59 UTC, wkoszek approved these changes
This looks much better

2022-06-17 19:59 UTC, wkoszek commented on config/conf.go
> +func CheckConfExit() {
@ramin0x53 remove it. You don't need it.

2022-06-17 19:59 UTC, wkoszek commented on config/conf.go
> +func CheckConfExit() {
Basically there's no need to check if file exists. You already have a read config function

If this function fails, it'll fail with the code in `err` saying `file doesn't exist`.

Other advantage is there there's no races between checking the file and when this file may get removed.

If you need preRun() just call Read Config there and simply return 'err'

2022-06-17 19:59 UTC, wkoszek commented on cmd/lpush.go
> +
Those newlines aren't necessary

2022-06-17 19:59 UTC, wkoszek commented on cmd/root.go
> +var (
I'll merge it, but it'd be nice if you found ways of not having global variables, that would be better

2022-06-18 05:34 UTC, wkoszek commented
@ramin0x53 You're not requesting the proper number of arguments in some commands:

```
wk@Wojciechs-MacBook-Air rcli % ./bin/rcli get
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/wkoszek/rcli/cmd.glob..func5(0x102fa3780, {0x102fd7ee8, 0x0, 0x0})
	/Users/wk/Desktop/rcli/cmd/get.go:22 +0x12c
github.com/spf13/cobra.(*Command).execute(0x102fa3780, {0x102fd7ee8, 0x0, 0x0})
	/Users/wk/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x102fa3280)
	/Users/wk/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/wk/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/wkoszek/rcli/cmd.Execute()
	/Users/wk/Desktop/rcli/cmd/root.go:39 +0x30
main.main()
	/Users/wk/Desktop/rcli/main.go:6 +0x20
```

2022-06-18 13:32 UTC, ramin0x53 commented on cmd/lpush.go
> +
Do you mean the empty line or `rootCmd.AddCommand(lpushCmd)` ?

2022-06-18 15:33 UTC, wkoszek commented on cmd/lpush.go
> +
newline mean 'empty line'

2022-06-18 15:34 UTC, wkoszek commented on Dockerfile
> +RUN apt update && apt install -y redis-server
@ramin0x53 you can merge both RUN commands.

2022-06-18 15:37 UTC, wkoszek commented on cmd/del.go
> +	PreRun: func(cmd *cobra.Command, args []string) {
@ramin0x53 Have you looked into `PersistentPreRun` in Cobra's documentation? Maybe we could just need this once in the root command?

2022-06-18 15:39 UTC, wkoszek commented on cmd/del.go
> +	Run: func(cmd *cobra.Command, args []string) {
Change all `Run` to `RunE`. Then you can just get an `err` variable and return it. All Println will become unnecessary

2022-06-18 16:55 UTC, ramin0x53 commented on cmd/root.go
> +var (
Why global variable is not good?

2022-06-18 17:03 UTC, ramin0x53 commented on cmd/del.go
> +	PreRun: func(cmd *cobra.Command, args []string) {
Yes , I looked into `PersistentPreRunE` , But after setting `PersistentPreRunE`, the config command does not work properly, bc It first checks the config file and then exit the app

2022-06-19 08:00 UTC, wkoszek commented on cmd/set.go
> +	Example: "rcli set name John",
here you should have https://golang.hotexamples.com/examples/github.com.docker.docker.cli/-/ExactArgs/golang-exactargs-function-examples.html

2022-06-19 08:01 UTC, wkoszek approved these changes
@ramin0x53 I'll merge it, but please submit a fix for the comment that I just submitted.

2022-06-19 08:01 UTC, merged